EMAIL_HOST_USER = "YOUR EMAIL"
EMAIL_HOST_PASSWORD = "YOUR HOST PASSWORD"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
SECRET_KEY = 'DJANGO SECURITY KEY'
