# Generated by Django 3.2.18 on 2023-04-20 09:25

import bikes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_photo',
            field=models.ImageField(upload_to=bikes.models.bikes_image_file_path),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_1',
            field=models.ImageField(blank=True, upload_to=bikes.models.bikes_image_file_path),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_2',
            field=models.ImageField(blank=True, upload_to=bikes.models.bikes_image_file_path),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_3',
            field=models.ImageField(blank=True, upload_to=bikes.models.bikes_image_file_path),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_photo_4',
            field=models.ImageField(blank=True, upload_to=bikes.models.bikes_image_file_path),
        ),
    ]
