on:
  push

jobs:
  test-lint:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      DJANGO_SECRET_KEY: '${{ secrets.DJANGO_SECRET_KEY }}'
    steps:
      - name: Print secret key
        run: echo "${{ secrets.DJANGO_SECRET_KEY }}"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Test
        run: |
          docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
